@extends('layouts.app')

@section('content')
<section class="hero"><div class="container hero-grid"><div class="hero-copy"><p class="eyebrow">Independent service studio <span>✳</span></p><h1>Move with<br><em>intention.</em></h1><p class="hero-lede">Nexa is a senior team of strategists, designers, and makers helping ambitious brands find their next right move.</p><div class="hero-actions"><a href="{{ route('services.index') }}" class="button button-accent">Explore services <span>↗</span></a><a href="#process" class="text-link">How we work <span>↓</span></a></div></div><div class="hero-art"><div class="art-ring"></div><div class="art-orb"></div><span class="art-caption">Strategy<br>Design<br>Momentum</span><span class="art-star">✦</span></div></div></section>
<section class="logo-strip"><div class="container logo-row"><span>Trusted by teams at</span><strong>ARC / ONE</strong><strong>northstar</strong><strong>LUCA</strong><strong>Field Notes</strong><strong>VANTA</strong></div></section>
<section class="section section-services"><div class="container"><div class="section-heading"><div><p class="eyebrow">What we do</p><h2>Good work starts<br>with a <em>clear move.</em></h2></div><a href="{{ route('services.index') }}" class="text-link">View all services <span>↗</span></a></div><div class="service-grid">@foreach($featuredServices as $service)<a class="service-card" href="{{ route('services.show', $service) }}"><div class="service-card-image" style="background-image:url('{{ $service->image_url }}')"><span class="service-icon">{{ $service->icon }}</span><span class="service-arrow">↗</span></div><p class="card-category">{{ $service->category }}</p><h3>{{ $service->title }}</h3><p>{{ $service->excerpt }}</p></a>@endforeach</div></div></section>
<section class="section split-section" id="about"><div class="container split-grid"><div class="split-visual"><div class="visual-block one"></div><div class="visual-block two"></div><span class="visual-note">Small team.<br>Big care.</span></div><div class="split-copy"><p class="eyebrow">The Nexa difference</p><h2>Less noise.<br><em>More signal.</em></h2><p>We are deliberately small so the people who win your trust are the people doing the work. No layers, no handoffs, no hiding behind a process.</p><p>Just thoughtful collaboration, sharp thinking, and a shared commitment to making something that matters.</p><a href="#process" class="button button-outline">Meet the approach <span>↗</span></a></div></div></section>
<section class="section process-section" id="process"><div class="container"><div class="section-heading"><div><p class="eyebrow">How we work</p><h2>A little structure<br>creates a lot of <em>space.</em></h2></div><p class="heading-aside">Every engagement is different. The care we bring to it is not.</p></div><div class="process-list"><div><span>01</span><h3>Find the signal</h3><p>We listen, question, and make sense of the messy middle.</p></div><div><span>02</span><h3>Make the move</h3><p>We turn insight into a clear direction and work you can use.</p></div><div><span>03</span><h3>Keep momentum</h3><p>We leave your team with the confidence to carry it forward.</p></div></div></div></section>
<section class="cta-section"><div class="container cta-inner"><p class="eyebrow">Your next chapter</p><h2>Have a good thing<br>in mind?</h2><a href="{{ route('services.index') }}" class="button button-accent">Let's make it real <span>↗</span></a></div></section>
@endsection
